---
output:
  pdf_document:
    keep_tex: true
    latex_engine: pdflatex

geometry: "top=2cm,bottom=2cm,left=2cm,right=2cm"
fontsize: 12pt
papersize: a4
header-includes:
  - \usepackage{graphicx}
  - \usepackage{fancyhdr}
  - \usepackage{titlesec}
  - \usepackage{geometry}
  - \usepackage[autostyle=true]{csquotes}
  - \usepackage[backend=bibtex, style=authoryear, natbib=true, sorting=nyt]{biblatex}
  - \usepackage[colorlinks, citecolor=blue, urlcolor=blue, linkcolor=blue, bookmarks=false]{hyperref}
  - \usepackage[table,xcdraw]{xcolor}
  - \usepackage{caption}
  - \usepackage{subcaption}
  - \usepackage{float}
  - \usepackage[toc, title, page]{appendix}
  - \usepackage{amsmath, amssymb}
  - \usepackage{lmodern}
  - \usepackage{eurosym}
  - \usepackage{pdflscape}
  - \usepackage{booktabs}
  - \usepackage{tabularx}
  - \usepackage{longtable}
  - \usepackage{bookmark}
  - \usepackage{emptypage}
  - \usepackage{flafter}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{pdfpages}
  - \usepackage{siunitx}
  - \usepackage{ebgaramond}
  - \usepackage[french]{babel}
  - \usepackage{ragged2e}
  - \usepackage{tocloft}
  - \usepackage{pdfpages}
  - \setstretch{1}
  - \setcounter{tocdepth}{2}
---

\begin{minipage}[t]{0.45\textwidth}
\raggedright
{\Large\textbf{Antoine Castet}}\\

---\\

22 place de l’Agronomie, Palaiseau \\
\href{mailto:antoine.castet@agroparistech.fr}{antoine.castet@agroparistech.fr} \\
+33 6 32 14 27 56 \\
\end{minipage}
\hfill
\begin{minipage}[t]{0.45\textwidth}
\raggedleft
Born on 27 November 1996 \\
French nationality \\
\href{https://sites.google.com/view/antoinecastet}{Website} \\
\href{https://ideas.repec.org/f/pca1705.html}{RePEc}\\
\href{https://scholar.google.com/citations?user=PAZtH9YAAAAJ&hl=fr}{GoogleScholar}
\end{minipage}

\vspace{0.2cm}

## Research Fields
\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\textbf{Primary:} Development economics

\textbf{Secondary:} Agricultural economics, Economic geography
\vspace{0.2cm}

## Current position
\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\textbf{Postdoctoral researcher}, AgroParisTech (CIRED)
\vspace{0.2cm}

## Doctoral Studies
\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
2020--2025
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\textbf{PhD in Development Economics}, Université Paris 1 Panthéon-Sorbonne
Supervised by Professor Alain Desdoigts, UMR Développement et Sociétés.
Jury: Rémi Bazillier, Christelle Dumas, Racha Ramadan, Raphaël Soubeyran
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
2023
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\textbf{Centre for Economic, Judicial, and Social Study and Documentation}
Visiting student at the CEDEJ (UMIFRE - CNRS) {Cairo, Egypt} 
Sponsor: \href{https://shs.cairn.info/publications-de-pascal-menoret--42012?lang=fr}{Pascal Menoret}
\end{minipage}




\begin{minipage}[t]{0.13\textwidth}
\raggedright
2017–2019
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Master’s degree in Development Economics}, Université Paris 1 Panthéon-Sorbonne\\
Master’s thesis: \textit{Minimum wage and firm performance: Evidence from Sub-Saharan Africa}\\
Supervised by Rémi Bazillier (Université Paris 1 Panthéon-Sorbonne)\\
\textit{Honours}
\end{minipage} 

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2014–2017
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Bachelor’s degree in Economics}, Université de Poitiers\\
\textit{Honours}
\end{minipage} 

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2014
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{French Baccalauréat in Economics and Social Sciences}, Lycée Pierre et Marie Curie, Châteauroux\\
\textit{Honours}
\end{minipage}


{\bfseries Centre for Economic, Judicial, and Social Study and Documentation} \hfill {2023} \\
 Visiting student at the CEDEJ (UMIFRE - CNRS) \hfill {Cairo, Egypt} \\
 Sponsor: \href{https://shs.cairn.info/publications-de-pascal-menoret--42012?lang=fr}{Pascal Menoret}
\vspace{0.2cm}

{\bfseries Cairo University} \hfill {2022} \\
 Visiting student at the Faculty of Economics and Political Science \hfill {Cairo, Egypt} \\
  Sponsor: \href{https://scholar.google.com/citations?user=VtX_EgwAAAAJ&hl=en}{Chahir Zaki}
\vspace{0.2cm}

## Pre-Doctoral Studies
\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

{\bfseries Panth\'{e}on-Sorbonne University} \hfill {2017 - 2019} \\
M.A in Development economics \hfill {Paris, France}
\vspace{0.2cm}

{\bfseries Poitiers University} \hfill {2014 - 2017} \\
B.A in Economics \hfill {Poitiers, France}
\vspace{0.2cm}

## References
\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\hspace{-0.5cm}
\begin{tabular}{p{5.5cm}p{5.5cm}p{5.5cm}}
\textbf{Prof. \href{https://scholar.google.com/citations?user=-IXkBZAAAAAJ\&hl=fr}{Rémi Bazillier}} &
\textbf{Prof. \href{https://scholar.google.com/citations?user=6c8QzJwAAAAJ\&hl=fr}{Alain Desdoigts}} &
\textbf{Prof. \href{https://scholar.google.com/citations?user=mImSYc4AAAAJ\&hl=fr\&oi=ao}{Karine Marazyan}} \\
Panth\'eon-Sorbonne, CES & Panth\'eon-Sorbonne, DEVSOC & Rouen Normandy, LERN \\
remi.bazillier@univ-paris1.fr & alain.desdoigts@univ-paris1.fr & karine.marazyan@univ-rouen.fr \\
\end{tabular}

\newpage

## Presentation

I am a postdoctoral researcher in economics at AgroParisTech, affiliated with the International Research Center on Environment and Development (CIRED). I am also an associate researcher at the UMR Développement et Sociétés (French National Research Institute for Sustainable Development – IRD / Université Paris 1 Panthéon-Sorbonne). I obtained my PhD in development economics from Université Paris 1 Panthéon-Sorbonne in July 2025.

As a development economist, my work lies at the intersection of agricultural economics and environmental and natural resource economics. It focuses mainly on agricultural productivity dynamics in Africa. I have in particular studied the effects of land-based investments on rural populations, as well as the impact of climate variability on employment and input use. To do so, I exploit data from household surveys, population censuses, and climate and spatial datasets. I use microeconometric methods to empirically identify the causal effect of the issues I analyse. In my research, I pay particular attention to the graphical representation of data and results, in order to facilitate their interpretation, strengthen the transparency of analyses and ensure clear communication. I have published some of this work in international journals such as *World Development* and the *Revue d’Économie du Développement*. I have also contributed to a book chapter focused on these topics. I have presented my research at national and international conferences such as the *International Conference on Development Economics* (ICDE), the annual conference of the *French Economic Association* (AFSE), and the World Congress of the *International Economic Association* (IEA). 

Alongside research, I contribute to teaching and scientific outreach. I taught at Sciences Po Paris for two years at the undergraduate level and also gave guest lectures in several Master’s programmes to present empirical methods used in economics. Actively involved in my research unit, I created a multidisciplinary seminar, organised a workshop dedicated to spatial data and contributed to various scientific events. Keen to contribute to the visibility of my field, I am also a member of the communication team of the *French Association for Development Economics* (AFEDEV).

This analytical CV first presents my academic and professional background. The second section details my teaching experience. The third section describes my research activities. Finally, the fourth section sets out the status of my publications and submissions.

## Profile and areas of specialisation

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

**Thematic fields:** 

\vspace{-5pt}

Development economics, agricultural economics, environmental and natural resource economics, applied econometrics

**Research topics:** 

\vspace{-5pt}

Agriculture, food insecurity, land-based investments, agricultural productivity, climate change, natural resources, structural transformation, Sub-Saharan Africa, Egypt

**Teaching experience:**
\vspace{-5pt}

Two years of undergraduate teaching (half-time ATER), 176 HETD

**Publications:**
\vspace{-5pt}

2 articles in international peer-reviewed journals, 1 chapter in an international peer-reviewed edited volume, 2 articles under review in international journals.
\newpage

# Academic and professional background
## Education

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
2020--2025
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\textbf{PhD in Development Economics, Université Paris 1 Panthéon-Sorbonne}\\
\textbf{Thesis:} \textit{Land investments and structural transformation in Africa}\\
Supervised by Professor Alain Desdoigts, UMR Développement et Sociétés.\\
Defence: 4 July 2025.

\textbf{Jury:}\\
Prof. Rémi Bazillier (Chair, Université Paris 1 Panthéon-Sorbonne)\\
Prof. Alain Desdoigts (Supervisor, Université Paris 1 Panthéon-Sorbonne)\\
Prof. Christelle Dumas (Referee, Université de Fribourg)\\
Prof. Racha Ramadan (Examiner, Cairo University)\\
D.R. Raphaël Soubeyran (Referee, INRAE)
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2017–2019
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Master’s degree in Development Economics}, Université Paris 1 Panthéon-Sorbonne\\
Master’s thesis: \textit{Minimum wage and firm performance: Evidence from Sub-Saharan Africa}\\
Supervised by Rémi Bazillier (Université Paris 1 Panthéon-Sorbonne)\\
\textit{Honours}
\end{minipage} 

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2014–2017
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Bachelor’s degree in Economics}, Université de Poitiers\\
\textit{Honours}
\end{minipage} 

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2014
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{French Baccalauréat in Economics and Social Sciences}, Lycée Pierre et Marie Curie, Châteauroux\\
\textit{Honours}
\end{minipage}


## Professional experience

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2025–2027
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Postdoctoral researcher} — AgroParisTech (CIRED), Paris, France\\
Position funded by the convergence institute CLAND. Supervised by Thierry Brunelle.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2023–2025 
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Temporary teaching and research assistant (ATER)} — Sciences Po, Paris, France.\\
Undergraduate courses: "Microeconomics" and "Introduction à l’économie".
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
May–June 2023
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Intern} — International Food Policy Research Institute (IFPRI), Cairo, Egypt\\
Launch of a research project that corresponds to the third chapter of my PhD thesis and is currently under revision at the \textit{Journal of Development Economics}.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
Jul–Oct 2020
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Research assistant} — Doctoral School 465, Paris, France\\
Cleaning and construction of databases based on information from Glottolog and the Ethnographic Atlas. Work carried out under the supervision of Étienne Le Rossignol, as part of the preparatory work for the article \href{https://www.nber.org/papers/w30259}{\textit{Ancestral Livelihoods and Moral Universalism: Evidence from Transhumant Pastoralist Societies}}, with Sara Lowes.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
Dec~2019–
Jun~2020
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Research assistant} — Sciences Po Paris (LIEPP), Paris, France\\
Data collection and analysis of a randomised controlled trial of the "Premier Campus" educational programme at Sciences Po Paris (2016–2017). Contribution to the drafting of the \href{https://www.sciencespo.fr/liepp/fr/recherche/projet/suivi-quantitatif-du-dispositif-premier-campus-sciences-po-2019-2021/}{\textit{quantitative evaluation of the Premier Campus programme}}.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
Sept–Dec 2019
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Research assistant} — Centre d’Économie de la Sorbonne, Paris, France\\
Database cleaning, literature review and exploratory work on the link between productivity and minimum wage in Africa. Work carried out under the supervision of Rémi Bazillier, as part of the preparatory work for the article \href{https://shs.hal.science/halshs-05016199}{\textit{Minimum Wage Shocks, Firms and Employment: Evidence from Africa}} with María Moraga-Fernández.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
Sept–Dec 2018
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Tutor in economics} — Université Paris 1 Panthéon-Sorbonne, Paris, France\\
Remedial classes in "Introduction générale à l’économie" for first-year undergraduate students facing difficulties.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
Jun–Aug 2018
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Intern} — International Food Policy Research Institute (IFPRI), Cairo, Egypt\\
Data processing and analysis for the conditional cash transfer project implemented by the World Bank: "Takaful and Karama".
\end{minipage}

\vspace{10pt}

## Organisation of conferences and seminars

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2025
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Member of the Organising Committee of the International Conference on Development Economics (ICDE)}. 
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2023–
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Member of the communication team of the French Association for Development Economics (AFEDEV)}
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2021–2024
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Co-organiser} with Jean-Baptiste Guiffard (UMR Développement \& Sociétés) and Karine Marazyan (LERN) of the methodological and multidisciplinary seminar \href{https://jeanbaptisteguiffard.github.io/automat.html}{Au Tour de Nos Matériaux} at UMR Développement et Sociétés, Nogent-sur-Marne. Obtained BQR funding and additional funding from the research unit to cover speakers’ travel expenses (2,850€).
\end{minipage}


\begin{minipage}[t]{0.13\textwidth}
\raggedright
2023
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Co-organiser} with Pascale Champalaune (PSE), Jean-Baptiste Guiffard (UMR Développement \& Sociétés) and Julia Paul-Venturine (PSE) of the \href{https://umr-devsoc.pantheonsorbonne.fr/evenements/journee-detudes-donnees-spatiales-nouvelles-sources-nouvelles-perspectives}{\textit{Workshop on spatial data in economics}} at UMR Développement et Sociétés, Nogent-sur-Marne. Obtained funding from PSE, the Sorbonne doctoral school of economics and UMR Développement et Sociétés for the organisation of the workshop (1,300€).
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2022
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Co-organiser} with Thomas Pernet (CES) and Laurine Wagner (Institut Acte) of the event \href{https://www.sorbonnetransition.org/symposium}{\textit{International Symposium of Sorbonne Sustainable Development}}.
\end{minipage}

## Invited research stays

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
May–June 2023
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Visiting student} at the Centre d’études et de documentation économiques, juridiques et sociales (CEDEJ), Cairo, Egypt.\\
Host: Prof. Pascal Menoret.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
May–Jul \\  
2022
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\textbf{Visiting student} at the Faculty of Economics and Political Science, Cairo University, Cairo, Egypt.\\
Host: Prof. Chahir Zaki.
\end{minipage}

## Language and IT skills

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

**French:** Native speaker.

**English:** Reading, writing, speaking. Daily use. 

**IT skills:** MS Office suite. Programming (R, STATA, Google Earth Engine, web scraping). Writing with \LaTeX and Rmarkdown. Mapping with QGIS.

\newpage

# Teaching

## Teaching experience in higher education (176 HETD)

\begin{tabular}{|c|c|c|c|}
\hline
\textbf{Level/Load} & \textbf{Courses} & \textbf{Tutorial-equivalent hours} & \textbf{Number of students} \\
\hline
\multicolumn{4}{|c|}{\textbf{Sciences Po Paris}} \\
\multicolumn{4}{|c|}{\textit{Academic year 2023–2024 – half-time ATER}} \\
\multicolumn{4}{|c|}{\textit{Course coordinator: Jean-Marc Robin.}} \\
\hline
L2 - Tutorial & Microeconomics & 24 h & 24 \\
\hline
L2 - Tutorial & Microeconomics & 24 h & 25 \\
\hline
L2 - Tutorial & Microeconomics & 24 h & 22 \\
\hline
L2 - Tutorial & Teaching assistant & 16 h & 108 \\
\hline
\multicolumn{4}{|c|}{\textbf{Sciences Po Paris}} \\
\multicolumn{4}{|c|}{\textit{Academic year 2024–2025 – half-time ATER}} \\
\multicolumn{4}{|c|}{\textit{Course coordinators: Jean-Marc Robin and Isabelle Méjean.}} \\
\hline
L1 - Tutorial & L’Économie & 24 h & 23 \\
\hline
L2 - Tutorial & Microeconomics & 24 h & 26 \\
\hline
L2 - Tutorial & Microeconomics & 24 h & 23 \\
\hline
L2 - Tutorial & Teaching assistant & 16 h & 88 \\
\hline

\multicolumn{4}{|c|}{\textbf{Université Paris-Saclay}} \\
\multicolumn{4}{|c|}{\textit{Year 2024 – Guest lecture}} \\
\multicolumn{4}{|c|}{\textit{Course coordinator: Pablo Rotelli.}} \\
\hline
M2 - Guest & Introduction à l'économie du développement & 1h30 & 10/15\\
\hline

\multicolumn{4}{|c|}{\textbf{Université de Rouen Normandie}} \\
\multicolumn{4}{|c|}{\textit{Year 2023 – Guest lecture}} \\
\multicolumn{4}{|c|}{\textit{Course coordinator: Karine Marazyan.}} \\
\hline
M2 - Guest & Introduction à l'économie du développement & 1h30 & 10/15\\
\hline

\multicolumn{4}{|c|}{\textbf{Institut d’études du développement de la Sorbonne}} \\
\multicolumn{4}{|c|}{\textit{Year 2023 – Guest lecture}} \\
\multicolumn{4}{|c|}{\textit{Course coordinator: Sylvie Capitant.}} \\
\hline
M1 - Guest & Introduction à l'économie du développement & 1h30 & 15/20\\
\hline

\multicolumn{4}{|c|}{\textbf{Université Paris 1 Panthéon-Sorbonne}} \\
\multicolumn{4}{|c|}{\textit{Year 2023 – Tutor}} \\
\multicolumn{4}{|c|}{\textit{Course coordinator: Jerome Lecointre.}} \\
\hline
L1 & Introduction générale à l’économie & 17h30 & 3/4\\
\hline
\end{tabular}

## Description of teaching activities

\(\bullet\) **Microeconomics (2023–2024) – Sciences Po Paris – 3 classes**

I taught the methodology conferences (equivalent to tutorials) for the Microeconomics course taught by Jean-Marc Robin, for three groups of students on the Reims campus. This second-year undergraduate course was taught in English.

The main objective was to build solid foundations in microeconomics for students with heterogeneous academic backgrounds. This required reviewing the mathematical tools needed to solve the exercises, in particular basic notions of differentiation. The sessions relied on strong student participation: most of the time was devoted to solving exercises presented on the board by students, under my supervision.

I contributed to drafting the midterm and final exams and was also responsible for grading them. As a teaching assistant, I was also responsible for assessing all students’ knowledge on a weekly basis through quizzes on Sciences Po’s Moodle platform and for mentoring the second instructor of the Microeconomics course in Reims.

The average satisfaction for this course, evaluated anonymously by students, was 72.3%.

\(\bullet\) **Microeconomics (2024–2025) – Sciences Po Paris – 2 classes**

Satisfied with my first year of teaching, Jean-Marc Robin requested that I continue teaching this course during my second year as an ATER, which I accepted. I also kept my role as teaching assistant. Following student feedback from the first year, I devoted a relatively large amount of time (about 30 minutes) at the beginning of each session to reviewing material taught in the lecture.

This seems to have been appreciated, as the average satisfaction for this course, evaluated anonymously by students, reached 91.8%.

\(\bullet\) **L’Économie (2024–2025) – Sciences Po Paris – 1 class**

This course, aimed at first-year undergraduate students, seeks to provide all Sciences Po students with a general economic culture. Indeed, many of them will not take further economics courses afterwards. The class assigned to me had the particularity of bringing together students enrolled in a dual degree between Sciences Po and Université Paris 1 Panthéon-Sorbonne (mathematics). I had great freedom in choosing teaching and assessment methods. I therefore replicated what I had done previously: a review of the lecture content for about thirty minutes, followed by the correction, under my supervision, of the exercises prepared by the students.

The average satisfaction for this course, evaluated anonymously by students, was 100.0%.

\newpage

# Presentation of research work
## PhD thesis overview

My PhD thesis consists of three chapters, each addressing distinct agricultural issues across the African continent.

The first chapter, published in *World Development*, studies the impact of large-scale land acquisitions on child malnutrition in ten African countries between 2005 and 2018. These investments can lead to the displacement of local farmers, the export of agricultural production to foreign markets, and a deterioration in the living conditions of workers employed on the new farms. Using a difference-in-differences approach, I exploit variation in children’s proximity to large-scale agricultural investment sites. To enable this analysis, I first improved the Land Matrix database by manually georeferencing 131 land deals. The results indicate that children living near these sites experience a deterioration in nutritional indicators after the land acquisition.

The second chapter evaluates the impact of large-scale agricultural expansion in the Egyptian desert. Thanks to significant public investments, the Egyptian government has sought to increase agricultural production and stimulate economic development in desert areas. These efforts could potentially benefit districts that actively participated in this expansion. To measure these effects, I use a difference-in-differences strategy, comparing districts that expanded into the desert to those that did not have this opportunity. The results show that although agricultural production increased in treated districts, this expansion did not promote structural transformation. On the contrary, these districts became more specialised in agriculture, a sector that is less conducive to long-term economic development.

The third chapter examines the consequences of climate change for structural transformation. To this end, I combine census data from 12 countries over a 40-year period (1974–2014) with climate data (temperature and precipitation). I find that higher temperatures increase the share of employment in agriculture, particularly among women and individuals with low levels of education. In contrast, changes in precipitation have a limited impact. The results suggest that this effect stems from a decline in agricultural productivity, which reduces the demand for manufactured goods and services, thereby slowing the development of these sectors. Overall, climate change appears to slow down structural transformation in Africa.

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

## Current and future research

My research, centred on agricultural issues in developing countries, is structured around three axes.

\(\bullet\) *Axis 1: Large-scale land acquisitions.*

The phenomenon of large-scale land acquisitions (land grabs, large-scale land acquisitions or LSLAs) has attracted significant scientific interest in the years following the 2008 food crisis. The Land Matrix Initiative has since played a central role by producing credible and well-documented data on these transactions. I contributed to this effort by geolocating numerous LSLAs. This allowed me to build an enriched database to analyse their effects on local populations. This work led to a publication in *World Development*.

In collaboration with a multidisciplinary group of researchers, I then extended this research in an article currently under revision at *Proceedings of the National Academy of Sciences*, examining typologies of LSLAs and the heterogeneity of their impacts.

The resurgence of LSLAs since the outbreak of the Russian–Ukrainian war underlines the current relevance of this topic. Recent advances in satellite data analysis, particularly for the spatial identification of LSLAs, enable me to envisage a project aimed at empirically validating all records in the Land Matrix database. This project seeks to understand the heterogeneity in the effective materialisation of LSLAs, many of which remain incomplete or abandoned.

\(\bullet\) *Axis 2: Climate change and its impacts on the agricultural sector.*

Climate change will disproportionately affect the African continent. Agriculture, which remains a major economic sector in many countries in the region, is highly climate-dependent. It is therefore important to study how the agricultural sector is affected by climate change. In joint work with Kibrom Abay (IFPRI) and Martin Paul Jr. Tabe-Ojong (World Bank), I use census data from 12 African countries to study how rising temperatures in recent decades have affected the share of agricultural employment. This article, currently under revision at the *Journal of Development Economics*, highlights how climate change disproportionately affects the most vulnerable populations.

Together with Martin Paul Jr. Tabe-Ojong, we plan to extend this work by exploiting the rich information in Demographic and Health Surveys (DHS) to observe changes in employment and food security among individuals living in areas where temperatures have increased. 

\(\bullet\) *Axis 3: Agricultural technologies and productivity gains.*

In my *Job Market Paper*, I study a policy of agricultural expansion implemented in the Egyptian desert. Thanks to substantial investments in irrigation canals, pumping systems, pivot irrigation and farm mechanisation, significant agricultural production has developed in these arid areas. Some of these technologies are labour-saving, while others improve yields but require a similar or even greater amount of labour. The effects of these productivity gains on agricultural employment are therefore ambiguous. My analysis shows that regions that expanded cultivated areas into the desert experienced a relatively stronger development of their agricultural sector than other regions, but at the expense of the manufacturing and service sectors, which are more conducive to long-term growth.

My postdoctoral research lies at the intersection of axes 2 and 3 and is carried out in collaboration with Thierry Brunelle and Tristan Le Cotty. Sub-Saharan Africa is characterised by low agricultural productivity, largely linked to limited use of inputs. The causes of this low adoption are multiple, but the high cost of inputs remains one of the main obstacles. Facing budget constraints, farmers often have to choose between buying fertilisers and buying pesticides. However, rising temperatures associated with climate change favour the proliferation of pests and diseases, leading farmers to prioritise crop protection expenditures (pesticides) over those aimed at increasing productivity (fertilisers). Using spatial data on fertiliser use, pesticide use and agricultural production, combined with a loss-aversion model, we aim to understand the determinants of agricultural productivity losses in the Kenyan context.

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

## Publications

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

**Articles in peer-reviewed journals (2)**

1. Castet A. (2024). The impact of Large-Scale Land Acquisitions on Food Security in Africa.  *World Development*, Volume 179, July 2024, 106597. doi: [10.1016/j.worlddev.2024.106597](https://www.sciencedirect.com/science/article/pii/S0305750X24000676).

Published in *World Development* (Rank A, CNU 05), this article, based on the first chapter of my thesis, analyses the effects of large-scale land acquisitions on the nutrition of children living nearby.

**Abstract:** Food insecurity is a major concern in most African countries. Large-scale land acquisitions (LSLAs) often have negative effects on local communities. In this article, I examine the impact of LSLAs on the nutritional status of children living nearby. To this end, I use a difference-in-differences methodology applied to LSLAs in a large number of African countries at different periods since the early 2000s. I analyse data from Demographic and Health Surveys (DHS), combined with data from the Land Matrix Initiative and supplemented by my own research, covering a total of 18,276 children living near 45 LSLAs.
The results show that LSLAs have had a significant negative effect on child nutrition in Africa over the last two decades. More specifically, dietary diversity scores of children living near LSLAs decreased by 20% after the acquisition. These results are robust to various statistical checks. No changes are observed in household employment status or assets. Although LSLAs may have positive effects on some agricultural practices, they are detrimental to children’s food security. This analysis underscores the importance of supporting local communities in the wake of foreign agricultural investments.

2. Castet, A. and Ramadan, R. (2023). Food security put to the test by COVID-19: An analysis of the MENA region. *Revue d’Économie du Développement*, 542, 99–123. doi: [10.3917/edd.373.0029](https://doi.org/10.3917/edd.373.0029).

Published in the *Revue d’Économie du Développement* (Rank B, CNU 05), in a special issue linked to the ICDE conference, this article analyses the effects of the COVID-19 pandemic on food security in five Middle Eastern and North African countries.

**Abstract:** We study the food situation of households in five countries in the Middle East and North Africa region during the COVID-19 pandemic. We show that household food security was negatively affected during the pandemic.

**Book chapter (1)**

1. Ramadan, R. and Castet, A. (2025). 4 Past, present and future of food security in Egypt. Pathways to African Food Security: Challenges, Threats and Opportunities towards 2050, edited by Michiel de Haas and Ken Giller. doi: [10.4324/9781032649696](https://doi.org/10.4324/9781032649696)

This chapter is part of a volume devoted to analysing the future dynamics of food security in Africa. Racha Ramadan, a specialist in food security in Egypt and lead author of the chapter, invited me to contribute, notably by producing the figures and writing the section on the country’s agricultural situation.

## *Working papers*

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

1. **The Conquest of the Desert: Land Investment in Egypt**

This article, my Job Market Paper and the second chapter of my thesis, analyses a policy of agricultural expansion in the Egyptian desert and its effects on structural transformation in the country.

**Abstract:** In Egypt, demographic pressure is pushing people to settle and farm the desert. To stimulate economic development, the government encourages these pioneers to settle there and contribute to the expansion of agriculture, industry and services. The desert thus concentrates the dreams and hopes of a country facing numerous challenges.
My study uses census and satellite data to analyse the effects of this expansion policy. To evaluate its impact on structural transformation, I use a difference-in-differences strategy, comparing districts bordering the desert to those located further inland, before and after the implementation of a law that accelerated this expansion. Census data, available from 1960 to 2017, allow for a long-term perspective.
Districts with access to the desert, and hence the possibility of expanding agricultural land, experienced a relative increase in the share of agricultural employment, accompanied by a relative decline in employment in industry and services, compared with other districts. These areas specialised in the sector where they enjoy a comparative advantage: agriculture.
Thus, the Egyptian expansion policy, instead of fostering the growth of manufacturing and service sectors, slowed the structural transformation of these districts relative to those located further inland.

2. **Heterogeneous impacts of large scale land acquisitions on child nutrition in the Global South** — with Julie Faure, Leonardo Bertassello, Davide Danilo Chiarelli, Sandra Eckert, Kyle Frankel Davis, Jampel Dell’Angelo, Paolo D’Odorico, Maria Cristina Rulli, Bhoktear Khan, and Marc F. Müller.

This article, currently in second-round *Revise and Resubmit* at *Proceedings of the National Academy of Sciences*, proposes a classification and analysis of the effects of different types of large-scale land acquisitions on the nutrition of children living nearby. Julie Faure and Marc F. Müller are the lead authors.

**Abstract:** Transnational land-based investments have increased sharply in recent decades, transforming rural landscapes in low- and middle-income countries. These large-scale land acquisitions (LSLAs) often displace smallholder agriculture and degrade natural ecosystems, disrupting local food, water and environmental systems. Yet the interactions between these socio-environmental transformations and their impact on household welfare remain poorly understood.
We present a global analysis of more than 400 georeferenced land deals, using a classification algorithm to characterise trade-offs across dimensions and define archetypes of LSLAs with distinct policy relevance. By linking these archetypes to data on more than 84,000 children from Demographic and Health Surveys, we show that effects on dietary diversity vary widely across archetypes, influenced by prior land use, water availability and the investment’s primary purpose.
The most negative effects arise when LSLAs involve conversion towards cash-crop agriculture or plantations. Conversely, some investments — in particular those located in already intensive agricultural regions — appear to improve dietary diversity, likely through local economic spillovers. However, these gains disappear under water scarcity. Strikingly, we find a persistent association between water scarcity and adverse nutritional outcomes, suggesting that the grabbing of water resources is a frequent and consequential feature of LSLAs.
Our results challenge the view of LSLAs as homogeneous interventions and underscore the need for more differentiated and context-specific policy responses. Regulation should target the socio-environmental trade-offs specific to each type of land investment in order to better protect household welfare in affected regions.

3. **Climate Change and Gendered Structural Transformation in Africa** — with Kibrom Abay (IFPRI) and Martin Paul Jr. Tabe-Ojong (World Bank).

This article, currently in *Revise and Resubmit* at the *Journal of Development Economics* and the third chapter of my thesis, analyses the effect of climate change on structural transformation in twelve African countries. I am the lead author.

**Abstract:** We examine whether and how climate change affects structural transformation in Africa. We also analyse gender-differentiated impacts and heterogeneities across population groups. Combining census data from 12 African countries over four decades (1974–2014) with spatially explicit data on temperature and precipitation, we show that a 1°C increase in average decadal temperature raises agricultural employment by about 6 percentage points, while leading to a comparable decline in the share of employment in non-agricultural sectors.
We also document heterogeneous impacts of climate change and show that it induces a gendered delay in structural transformation, with women and less-educated individuals more affected by this climate-induced slowdown. These results suggest that climate change may exacerbate existing inequalities within societies.
Finally, we provide empirical evidence on potential mechanisms, notably those related to agricultural productivity and labour market participation. In the medium term, rising temperatures reduce agricultural productivity while increasing demand for agricultural labour and, consequently, labour force participation.

## Ongoing research projects

\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

1. **The Economic Analysis of Maize Intensification in Kenya** (2025) — with Thierry Brunelle and Tristan Le Cotty.

## Presentations in seminars and international conferences 

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2025
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\href{https://afedev.fr/2025/06/05/call-for-papers-journees-doctorales-du-developpement-job-market-les-16-et-17-octobre-2025-a-bordeaux/}{JDD - Job Market}, Bordeaux School of Economics, Bordeaux, France.\\
\href{https://www.osservatorio-economie-emergenti-torino.it/our-activities/478-call-for-paper-11th-workshop-oeet.html}{11th Workshop OEET}, Collegio Carlo Alberto, Turin, Italy.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2024
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\href{https://economix.fr/en/colloques-et-workshops/crises-and-resilience-in-developing-countries}{Crises and resilience in developing countries workshop}, Université Saint-Joseph de Beyrouth, Beirut, Lebanon.
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2023
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\href{https://erf.org.eg/events/erf-29th-annual-conference-the-future-of-mena-development-path-risks-and-opportunities-in-an-emerging-world-order/}{ERF 29th annual conference (Economic Research Forum)}, Cairo, Egypt.\\
\href{https://icde2023.sciencesconf.org/}{International Conference on Development Economics (ICDE)}, Paris School of Economics, Paris, France.\\
\href{https://afse2023.sciencesconf.org/}{71st Congress of the French Economic Association (AFSE)}, Sciences Po, Paris, France.\\
\href{https://www.nordev2023.se/}{7th Nordic Development Research Conference}, Uppsala University, Uppsala, Sweden.\\
UMR Développement \& Sociétés/CIRED PhD Poster Session, Paris, France.\\
\href{https://fesp-eg.org/wp-content/uploads/2023/03/Call_9thFEPS_Paris1.pdf}{9th FESP-Paris 1 Research Workshop}, Université Paris 1 Panthéon-Sorbonne, Paris, France.\\
UMR Développement \& Sociétés PhD Seminar, Université Paris 1 Panthéon-Sorbonne, Paris, France.\\
\href{https://umr-devsoc.pantheonsorbonne.fr/evenements/journee-detudes-donnees-spatiales-nouvelles-sources-nouvelles-perspectives}{Workshop on spatial data in economics}, Université Paris 1 Panthéon-Sorbonne, Paris, France.\\
\href{https://ieawc2023.org/}{20th World Congress of the International Economic Association}, Universidad EAFIT, Medellin, Colombia.\\
\end{minipage}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2022
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
\href{https://afedev.fr/journees-doctorales-du-developpement-2022/}{Journées Doctorales du Développement}, Université Paris 1 Panthéon-Sorbonne, Paris, France.\\
\href{https://sites.google.com/site/doctorissimes3/previous-doctorissimes-conferences/17th-doctorissimes-2022}{17th Doctorissimes PhD Conference}, Paris School of Economics, Paris, France.\\
\href{https://ug.edu.gh/announcement/policy-conference-policies-sustainable-rural-transformation-africa}{MIASA policy conference}, University of Ghana, Accra, Ghana.\\
\href{https://icde2022.sciencesconf.org/}{International Conference on Development Economics (ICDE)}, Université Clermont Auvergne, Clermont-Ferrand, France.\\
\href{https://fesp-eg.org/wp-content/uploads/2023/03/Agenda-FESP-Paris1-2022.pdf}{Eighth Research Workshop FESP-Paris 1}, Cairo, Egypt.\\
\href{https://www.sorbonnetransition.org/symposiumInternational}{Symposium of Sorbonne Sustainable Development}, Université Paris 1 Panthéon-Sorbonne, Paris, France.\\
UMR 7206 "Éco-Anthropologie" Seminar, Muséum national d’Histoire naturelle, Paris, France.\\
\href{https://iedes.pantheonsorbonne.fr/evenements/iedes-eadi-france-journee-detude-internationale}{EADI conference}, Agence Française de Développement, Paris, France.
\end{minipage}

## Awards and funding

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

\begin{minipage}[t]{0.13\textwidth}
\raggedright
2023–2027
\end{minipage}
\hfill
\begin{minipage}[t]{0.85\textwidth}
\justifying
Member of the ANR JuGe project (Women and marital conflicts in West Africa: A comparative study of two historical and contemporary conflict resolution mechanisms) coordinated by Karine Marazyan, Charlotte Guénard and Paola Villar (300,000€).
\end{minipage}

## Other scientific activities

\vspace{-20pt}
\noindent\rule{\textwidth}{0.2pt}

- **Referee for peer-reviewed journals**: *Food Security*; *World Development* ($\times 2$)
