---
output:
  pdf_document:
    latex_engine: pdflatex
geometry: left=0.75in,top=1in,right=0.75in,bottom=1in
documentclass: resume
header-includes:
  - \usepackage{graphicx}
  - \usepackage[T1]{fontenc}
  - \usepackage[utf8]{inputenc}
  - \usepackage[official]{eurosym}
  - \usepackage{fontawesome}
  - \usepackage{multicol}
  - \usepackage[normalem]{ulem}
  - \usepackage[colorlinks=true,linkcolor=cyan,urlcolor=black]{hyperref}
---

\vspace{-2.25cm}

\begin{center}
\LARGE{\bfseries Antoine Castet}\\
\vspace{0.1cm}
\normalsize
\end{center}
\vspace{0.1cm}

\noindent\begin{tabular}{p{0.62\textwidth} p{0.34\textwidth}}
\textbf{Coordonnées} & \textbf{Informations personnelles} \\
\href{mailto:antoine.castet@agroparistech.fr}{antoine.castet@agroparistech.fr} & Nationalité : Française \\
22 place de l'Agronomie, Palaiseau & Né en 1996 \\
+33 6 32 14 27 56 &  \href{https://antoinecastet.github.io/AntoineCastet/}{Site web} \\

\end{tabular}
\vspace{0.1cm}

\begin{small}
\begin{rSection}{Poste actuel}
{\bfseries Chercheur postdoctoral}, AgroParisTech (CIRED) \hfill {2025 - 2027} 
\end{rSection}

\begin{rSection}{Études}
{\bfseries Université Panthéon-Sorbonne} \hfill {2020 - 2025} 
\\ Doctorat en économie du développement  \hfill {Paris, France} \\ 
Directeur de thèse : \href{https://scholar.google.com/citations?user=6c8QzJwAAAAJ&hl=fr}{Alain Desdoigts} \\
Jury : \href{https://scholar.google.com/citations?user=-IXkBZAAAAAJ&hl=fr}{Rémi Bazillier}, \href{https://scholar.google.com/citations?user=WtNVDgMAAAAJ&hl=fr}{Christelle Dumas}, \href{https://scholar.google.com/citations?user=OH-yKZQAAAAJ&hl=en}{Racha Ramadan} et \href{https://scholar.google.fr/citations?user=Iv0Mq7wAAAAJ&hl=ru}{Raphaël Soubeyran}
\vspace{0.05cm}

{\bfseries Centre d'études et de documentation économiques, juridiques et sociales} \hfill {2023} \\
 Étudiant visiteur au CEDEJ (UMIFRE - CNRS) \hfill {Le Caire, Égypte} \\
 Référent : \href{https://shs.cairn.info/publications-de-pascal-menoret--42012?lang=fr}{Pascal Menoret}
\vspace{0.1cm}

{\bfseries Université du Caire} \hfill {2022} \\
 Étudiant visiteur à la Faculté d'économie et de science politique \hfill {Le Caire, Égypte} \\
  Référent : \href{https://scholar.google.com/citations?user=VtX_EgwAAAAJ&hl=en}{Chahir Zaki}
\vspace{0.1cm}

{\bfseries Université Panthéon-Sorbonne} \hfill {2017 - 2019} \\
Master en économie du développement \hfill {Paris, France}
\vspace{0.1cm}

{\bfseries Université de Poitiers} \hfill {2014 - 2017} \\
Licence en économie \hfill {Poitiers, France}
\end{rSection}
\vspace{0.1cm}

\begin{rSection}{Publications}
\begin{enumerate}
\item \textbf{The impact of large-scale land acquisitions on food security in Africa} \\
\href{https://www.sciencedirect.com/science/article/pii/S0305750X24000676}{\uline{World Development}}, vol. 179, 2024. \href{https://antoinecastet.github.io/AntoineCastet/PDF/aa8269af-a102-4e7c-9a76-0427fdb18943.pdf}{\uline{PDF}}
\item \textbf{Food security and Covid-19: An analysis of the MENA region}, avec \href{https://scholar.google.com/citations?user=OH-yKZQAAAAJ&hl=en}{Racha Ramadan} \\
\href{https://shs.cairn.info/revue-d-economie-du-developpement-2023-3-page-29?tab=resume}{\uline{Revue d'Économie du Développement}}, vol. 35, 2023. \href{https://antoinecastet.github.io/AntoineCastet/PDF/castet-2023-la-securite-alimentaire-a-lepreuve-du-covid-19-une-analyse-de-la-region-moan.pdf}{\uline{PDF}} \\
\end{enumerate}
\end{rSection}

\begin{rSection}{Travaux en cours}
\begin{enumerate}
\item \textbf{The Conquest of the Desert: Land Investment in Egypt}. \\
Article sur le marché du travail académique.
\item \textbf{Heterogeneous impacts of large scale land acquisitions on child nutrition in the Global South}, avec \href{https://scholar.google.com.tw/citations?user=S2iiM2kAAAAJ&hl=ja}{Julie Faure}, \textit{et al}. et \href{https://scholar.google.com/citations?user=jnHeBrcAAAAJ&hl=en}{Marc F. Müller}. \\
Révision et resoumission à \uline{Proceedings of the National Academy of Sciences}.

\item \textbf{Climate Change and Gendered Structural Transformation in Africa}, avec \href{https://scholar.google.com/citations?user=-ga5p8UAAAAJ&hl=en}{Kibrom Abay} et \href{https://scholar.google.com/citations?user=OwxVewYAAAAJ&hl=en}{Martin Paul Jr.Tabe-Ojong}.\\
Révision et resoumission à \uline{Journal of Development Economics}.

\item \textbf{The Economic Analysis of Maize Intensification}, avec Thierry Brunelle et Tristan Le Cotty.
\end{enumerate}
\end{rSection}

\begin{rSection}{Chapitre d'ouvrage}
\begin{enumerate}
\item \textbf{Past, Present and Future of Food Security in Egypt}, avec \href{https://scholar.google.com/citations?user=OH-yKZQAAAAJ&hl=en}{Racha Ramadan}, dans \href{https://www.routledge.com/Pathways-to-African-Food-Security-Challenges-Threats-and-Opportunities-towards-2050/deHaas-Giller/p/book/9781032649658?srsltid=AfmBOoolqrs77yqzKgOg8RmFGkxwCn5Cr-c30_HqrrUXbVyoELnq1QJ5}{\uline{Pathways to African Food Security: Challenges, Threats and Opportunities towards 2050}}, édité par \href{https://scholar.google.com/citations?user=8jBsupsAAAAJ&hl=en}{Michiel de Haas} et \href{https://scholar.google.com/citations?user=yct61VwAAAAJ&hl=fr}{Ken E. Giller}, 2025, \href{https://www.taylorfrancis.com/reader/download/f60b6d2e-a507-4c05-9a2f-cdde9916cbf5/chapter/pdf?context=ubx}{\uline{PDF}}
\end{enumerate}
\end{rSection}

\begin{rSection}{Expériences professionnelles}
\textbf{AgroParisTech - CIRED} \hfill{Sept 2025 - Sept 2027, Paris} \\
\textit{Chercheur postdoctoral} \\
\textbf{Sciences Po Paris} \hfill{Sept 2023 - Août 2025, Paris} \\
\textit{Attaché temporaire d'enseignement et de recherche (ATER)} \\
\textbf{Institut international de recherche sur les politiques alimentaires} \hfill{Mai-Juin 2023, Le Caire} \\
\textit{Stagiaire} \\
\textbf{\'Ecole doctorale 465 - Economie Panth\'eon-Sorbonne} \hfill {Juillet-Octobre 2020, Paris} \\
\textit{Assistant de recherche pour \href{https://etiennelerossignol.wordpress.com/}{Etienne Le Rossignol} - Doctorant}\\
\textbf{Sciences Po Paris - LIEPP} \hfill {Déc 2019-Juin 2020, Paris} \\
\textit{Assistant de recherche pour \href{https://scholar.google.fr/citations?user=FC7RktsAAAAJ&hl=fr}{Denis Fougère} - Directeur de recherche CNRS} \\
\textbf{Centre d'\'Econonomie de la Sorbonne - UMR8174} \hfill{Sept-Déc 2019, Paris} \\
\textit{Assistant de recherche pour \href{https://scholar.google.com/citations?user=-IXkBZAAAAAJ\&hl=fr}{Rémi Bazillier} - Professeur des universités} \\
\textbf{Université Panthéon-Sorbonne}\hfill{Sept-Déc 2018, Paris} \\
\textit{Tuteur en économie}\\
\textbf{Institut international de recherche sur les politiques alimentaires} \hfill{Juin-Août 2018, Le Caire} \\
\textit{Stagiaire}\\
\end{rSection}

\begin{rSection}{Enseignement}
\textbf{Institut d'études du développement de la Sorbonne} \hfill {2026} \\
Introduction à Stata (master)  \\
Tutorat en économie (master)  \\
\textbf{Ecole Polytechnique} \hfill {2026} \\
Applied Econometrics (master)  \\
\textbf{Sciences Po Paris} \hfill {2024-2025} \\
Microéconomie (licence), chargé de TD du Pr. \href{https://scholar.google.com/citations?user=tt48sngAAAAJ&hl=fr}{Jean-Marc Robin}  \\
Introduction à l'économie (licence) \\
\textbf{Sciences Po Paris} \hfill {2023-2024} \\
Microéconomie (licence), chargé de TD du Pr. \href{https://scholar.google.com/citations?user=tt48sngAAAAJ&hl=fr}{Jean-Marc Robin}  \\
\end{rSection}

\begin{rSection}{Activités scientifiques}
\textbf{ICDE} - Membre du comité d'organisation \hfill {2025-2026}\\
\textbf{JDD} - Membre du comité scientifique et d'organisation \hfill {2025-2026}\\
\textbf{AFEDEV} - Membre de l'équipe de communication \hfill {2023-}\\
\textbf{Séminaire AuToMat} - Co-fondateur \hfill {2021-2024}\\
\href{https://www.parisschoolofeconomics.eu/en/events/workshop-on-spatial-data-new-sources-new-perspectives-1-december/ } {\textbf{Atelier sur les données spatiales}} - Co-organisateur \hfill {2023} \\

\textbf{Relecture} \textit{Food Security, World Development ($\times 2$)}
\end{rSection}
\vspace{0.2cm}
\end{small}
